// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAakenw944cQzlmN8tQh0XkDJGkJS1Zor0',
    appId: '1:764352376468:web:ba61b54dbf7e65cfe94e81',
    messagingSenderId: '764352376468',
    projectId: 'chamasoft-lite',
    authDomain: 'chamasoft-lite.firebaseapp.com',
    storageBucket: 'chamasoft-lite.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS_B0Lw3PTqqB6TJfk3hzWSfIAWh7I0zA',
    appId: '1:764352376468:android:ba6c5b0d9f2b827ee94e81',
    messagingSenderId: '764352376468',
    projectId: 'chamasoft-lite',
    storageBucket: 'chamasoft-lite.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMBRnQcSkdByFSqIcbySUAI2BqVEfQ6Bw',
    appId: '1:764352376468:ios:c3f94f9e08446495e94e81',
    messagingSenderId: '764352376468',
    projectId: 'chamasoft-lite',
    storageBucket: 'chamasoft-lite.appspot.com',
    iosClientId: '764352376468-03m77rh6tjvh1u95b7oo9nvlbeu9pddp.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMBRnQcSkdByFSqIcbySUAI2BqVEfQ6Bw',
    appId: '1:764352376468:ios:064c8e1040596a1be94e81',
    messagingSenderId: '764352376468',
    projectId: 'chamasoft-lite',
    storageBucket: 'chamasoft-lite.appspot.com',
    iosClientId: '764352376468-2c5ndekfc1rv30425qu1fpckr9gv1mr6.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationsApp.RunnerTests',
  );
}
